# Copyright 2017, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START memteach_app_yaml]
runtime: nodejs10
instance_class: F1
automatic_scaling:
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 1500ms
  max_pending_latency: 1500ms
  max_concurrent_requests: 80
handlers:
- url: /.*
  script: auto
# [END memteach_app_yaml]
