#
# Copyright (c) 2020, Vitalii Savinov, vitsavinov@gmail.com
# Licensed under the ISC License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at https://www.isc.org/licenses/
#

# [START memteach_app_yaml]
runtime: nodejs10
instance_class: F2
automatic_scaling:
  min_instances: 0
  max_instances: 3
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 1500ms
  max_pending_latency: 1500ms
  max_concurrent_requests: 80
handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /memory.css
  static_files: memory.css
  upload: memory.css
- url: /memory-bundle.js
  static_files: memory-bundle.js
  upload: memory-bundle.js
- url: /data/(.*)
  static_files: data/\1
  upload: data/(.*)
- url: /img/(.*\.(gif|png|jpg))$
  static_files: img/\1
  upload: img/.*\.(gif|png|jpg)$
# [END memteach_app_yaml]
